global:
  scrape_interval: 60s
remote_write:
  - url: $GF_URL
    basic_auth:
      username: $GF_USERNAME
      password: $GF_PASSWORD
scrape_configs:
  - job_name: node
    static_configs:
      - targets:
          - 'app:3000'