/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/door.gltf --t --o components/door/door.tsx 
*/

import React, { useEffect } from 'react';
import { GLTFResult } from './type';
import { DoorState } from '../store';
import { Frame } from 'lucide-react';

interface FrameProps {
  result: GLTFResult;
  storage: DoorState;
}

export function DoorFrame({ result, storage }: FrameProps) {
  const { nodes, materials } = result;

  return <group></group>;
}
