/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/models/door.gltf --t --o components/door/door.tsx 
*/

import React, { useEffect, useMemo, useState } from 'react';
import { useGLTF } from '@react-three/drei';
import { ANIMATION_SPEED, GLTFResult, Scale } from './type';
import { useDoorStore } from '../store';
import {
  Group,
  Mesh,
  MeshPhysicalMaterial,
  MeshPhysicalMaterialParameters,
  MeshStandardMaterial,
  MeshStandardMaterialParameters,
  Object3DEventMap,
  TextureLoader,
} from 'three';
import { useFrame, useLoader } from '@react-three/fiber';
import { HoneyComb } from './honeycomb';
import { DoorLeaf } from './door-leaf';
import { Hinge } from './hinge';
import { Frame } from './frame';
import { Architrave } from './architrave';
import variants from '../../../public/variants.json';

interface LoadMaterialProps {
  variantCode: string;
  defaultMaterial: MeshStandardMaterial;
}

function LoadMaterial({ variantCode, defaultMaterial }: LoadMaterialProps) {
  const newMeshPhysicalMaterial = (params: MeshPhysicalMaterialParameters) =>
    new MeshPhysicalMaterial({
      name: variantCode,
      roughness: 0.5,
      metalness: 0,
      specularIntensity: 0,
      reflectivity: 0.4591837131892669,
      side: 2,
      ...params,
    });

  const textureUrl = variants.find(
    (variant) => variant.data.code === variantCode
  )?.data.file.url;

  if (!textureUrl) {
    return defaultMaterial;
  }

  const texture = useLoader(TextureLoader, textureUrl);
  if (texture) {
    texture.flipY = true;
    texture.colorSpace = 'srgb';
  }

  const material = useMemo(() => {
    const newMaterial = newMeshPhysicalMaterial({
      map: texture,
    });
    return newMaterial;
  }, [texture]);

  return material;
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const result = useGLTF('/models/door.gltf') as GLTFResult;
  const { nodes, materials } = result;
  const storage = useDoorStore();
  const DOOR_SCALE: Scale = {
    width: storage.size.width / 83,
    height: storage.size.height / 210,
  };

  const honeyCombMaterial = materials.mdf;
  const doorMaterial = LoadMaterial({
    variantCode: storage.finishingVariant?.name ?? '',
    defaultMaterial: materials.mdf,
  });

  const doorGroupRef = React.useRef<Group<Object3DEventMap> | null>(null);
  const handleRef = React.useRef<Mesh | null>(null);
  const keyRef = React.useRef<Mesh | null>(null);
  const doorLockRef = React.useRef<Mesh | null>(null);

  useFrame(() => {
    if (doorGroupRef.current) {
      const y =
        DOOR_SCALE.height < 1 ? DOOR_SCALE.height : DOOR_SCALE.height * 1.005;

      doorGroupRef.current.scale.lerp(
        { x: DOOR_SCALE.width, y: y, z: 1 },
        ANIMATION_SPEED
      );
    }
    if (doorLockRef.current) {
      doorLockRef.current.position.lerp(
        {
          x: -0.019 * (DOOR_SCALE.width - 1),
          y: 1.1 * (DOOR_SCALE.height - 1),
          z: 0,
        },
        ANIMATION_SPEED
      );
    }
    if (handleRef.current) {
      handleRef.current.position.lerp(
        {
          x: 0.065 * (DOOR_SCALE.width - 1),
          y: 1.1 * (DOOR_SCALE.height - 1),
          z: 0,
        },
        ANIMATION_SPEED
      );
    }
    if (keyRef.current) {
      keyRef.current.position.lerp(
        {
          x: 0.065 * (DOOR_SCALE.width - 1),
          y: 1 * (DOOR_SCALE.height - 1),
          z: 0,
        },
        ANIMATION_SPEED
      );
    }
  });

  return (
    <group {...props} dispose={null}>
      <group ref={doorGroupRef}>
        {storage.finishing ? (
          <DoorLeaf
            gltfResult={result}
            name={storage.groove?.name ?? ''}
            material={doorMaterial}
          />
        ) : (
          <HoneyComb gltfResult={result} material={honeyCombMaterial} />
        )}
      </group>
      {storage.hinge?.isAdded && (
        <Hinge gltfResult={result} DOOR_SCALE={DOOR_SCALE} />
      )}
      <Frame
        gltfResult={result}
        material={doorMaterial}
        DOOR_SCALE={DOOR_SCALE}
      />
      <Architrave
        gltfResult={result}
        material={doorMaterial}
        DOOR_SCALE={DOOR_SCALE}
      />
      {storage.key?.isAdded && (
        <mesh
          geometry={nodes.DoorKey.geometry}
          material={materials.chrome2}
          ref={keyRef}
        />
      )}
      {storage.handle?.isAdded && (
        <mesh
          geometry={nodes.DoorHandle.geometry}
          material={materials.chrome2}
          ref={handleRef}
        />
      )}
      {storage.cylinder?.isAdded && (
        <mesh
          geometry={nodes.DoorLock.geometry}
          material={materials.chrome2}
          ref={doorLockRef}
        />
      )}
    </group>
  );
}

useGLTF.preload('/models/door.gltf');
