/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/door.gltf --t --K --o components/door/door.tsx 
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Easy_1: THREE.Mesh;
    Easy_2: THREE.Mesh;
    Hard_1: THREE.Mesh;
    Hard_2: THREE.Mesh;
    Hole: THREE.Mesh;
    Medium_1: THREE.Mesh;
    Medium_2: THREE.Mesh;
    Solid: THREE.Mesh;
    Paper1: THREE.Mesh;
    Paper2: THREE.Mesh;
    Paper3: THREE.Mesh;
    Paper4: THREE.Mesh;
    Paper5: THREE.Mesh;
    Paper6: THREE.Mesh;
    Paper7: THREE.Mesh;
    Paper8: THREE.Mesh;
    HoneyCombFrame: THREE.Mesh;
    BackTopFrame: THREE.Mesh;
    FrontTopFrame: THREE.Mesh;
    BackLeftFrame: THREE.Mesh;
    FrontLeftFrame: THREE.Mesh;
    DoorHandle: THREE.Mesh;
    DoorKey: THREE.Mesh;
    DoorLock: THREE.Mesh;
    BackRightFrame: THREE.Mesh;
    FrontRightFrame: THREE.Mesh;
    BackLeftArch: THREE.Mesh;
    FrontLeftArch: THREE.Mesh;
    BackRightArch: THREE.Mesh;
    FrontRightArch: THREE.Mesh;
    BackTopArch: THREE.Mesh;
    FrontTopArch: THREE.Mesh;
    Hinge: THREE.Mesh;
  };
  materials: {
    melamine: THREE.MeshStandardMaterial;
    ducoBlack: THREE.MeshStandardMaterial;
    cardboard: THREE.MeshStandardMaterial;
    mdf: THREE.MeshStandardMaterial;
    tacoHpl: THREE.MeshStandardMaterial;
    chrome2: THREE.MeshPhysicalMaterial;
    tacoSheet: THREE.MeshStandardMaterial;
  };
  animations: [];
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/door.gltf') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group>
        <group>
          <group>
            <mesh
              geometry={nodes.Easy_1.geometry}
              material={materials.melamine}
            />
            <mesh
              geometry={nodes.Easy_2.geometry}
              material={materials.ducoBlack}
            />
          </group>
          <group scale={[0.989, 1, 1]}>
            <mesh
              geometry={nodes.Hard_1.geometry}
              material={materials.melamine}
            />
            <mesh
              geometry={nodes.Hard_2.geometry}
              material={materials.ducoBlack}
            />
          </group>
          <mesh geometry={nodes.Hole.geometry} material={materials.melamine} />
          <group>
            <mesh
              geometry={nodes.Medium_1.geometry}
              material={materials.melamine}
            />
            <mesh
              geometry={nodes.Medium_2.geometry}
              material={materials.ducoBlack}
            />
          </group>
          <mesh geometry={nodes.Solid.geometry} material={materials.melamine} />
        </group>
        <group>
          <group>
            <mesh
              geometry={nodes.Paper1.geometry}
              material={materials.cardboard}
              position={[0, -1.669, 0]}
            />
            <mesh
              geometry={nodes.Paper2.geometry}
              material={materials.cardboard}
              position={[0, -1.431, 0]}
            />
            <mesh
              geometry={nodes.Paper3.geometry}
              material={materials.cardboard}
              position={[0, -1.192, 0]}
            />
            <mesh
              geometry={nodes.Paper4.geometry}
              material={materials.cardboard}
              position={[0, -0.954, 0]}
            />
            <mesh
              geometry={nodes.Paper5.geometry}
              material={materials.cardboard}
              position={[0, -0.715, 0]}
            />
            <mesh
              geometry={nodes.Paper6.geometry}
              material={materials.cardboard}
              position={[0, -0.477, 0]}
            />
            <mesh
              geometry={nodes.Paper7.geometry}
              material={materials.cardboard}
              position={[0, -0.238, 0]}
            />
            <mesh
              geometry={nodes.Paper8.geometry}
              material={materials.cardboard}
            />
          </group>
          <mesh
            geometry={nodes.HoneyCombFrame.geometry}
            material={materials.mdf}
            position={[0.405, 2.052, 0.026]}
          />
        </group>
        <group position={[0.8, 2.1, 0.04]}>
          <mesh
            geometry={nodes.BackTopFrame.geometry}
            material={materials.tacoHpl}
            position={[-0.4, -2.1, -0.04]}
          />
          <mesh
            geometry={nodes.FrontTopFrame.geometry}
            material={materials.tacoHpl}
            position={[0, 0.005, 0]}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.BackLeftFrame.geometry}
            material={materials.tacoHpl}
          />
          <mesh
            geometry={nodes.FrontLeftFrame.geometry}
            material={materials.tacoHpl}
            position={[0, 1.05, 0.04]}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.DoorHandle.geometry}
            material={materials.chrome2}
          />
          <mesh
            geometry={nodes.DoorKey.geometry}
            material={materials.chrome2}
          />
          <mesh
            geometry={nodes.DoorLock.geometry}
            material={materials.chrome2}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.BackRightFrame.geometry}
            material={materials.tacoHpl}
          />
          <mesh
            geometry={nodes.FrontRightFrame.geometry}
            material={materials.tacoHpl}
            position={[0.81, 1.055, 0.04]}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.BackLeftArch.geometry}
            material={materials.tacoSheet}
          />
          <mesh
            geometry={nodes.FrontLeftArch.geometry}
            material={materials.tacoSheet}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.BackRightArch.geometry}
            material={materials.tacoSheet}
          />
          <mesh
            geometry={nodes.FrontRightArch.geometry}
            material={materials.tacoSheet}
          />
        </group>
        <group position={[-0.014, 2.137, 0]}>
          <mesh
            geometry={nodes.BackTopArch.geometry}
            material={materials.tacoSheet}
          />
          <mesh
            geometry={nodes.FrontTopArch.geometry}
            material={materials.tacoSheet}
          />
        </group>
        <mesh
          geometry={nodes.Hinge.geometry}
          material={materials.chrome2}
          position={[0.809, 2.034, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/door.gltf');
