// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.0 public/models/door.gltf --t --o components/door/door.tsx
// */

// import * as THREE from 'three'
// import React from 'react'
// import { useGLTF } from '@react-three/drei'
// import { GLTF } from 'three-stdlib'

// type GLTFResult = GLTF & {
//   nodes: {
//     ['2_Tali_Air_Horizontal']: THREE.Mesh
//     ['3_Tali_Air_Horizontal']: THREE.Mesh
//     ['3_Tali_Air_Vertikal']: THREE.Mesh
//     Daun_Pintu_Polos: THREE.Mesh
//     Engsel_Pintu: THREE.Mesh
//     ['Handel_&_Kunci_Pintu']: THREE.Mesh
//     Rangka_Honey_Comb001: THREE.Mesh
//     ArchFrontLeft: THREE.Mesh
//     ArchFrontRight: THREE.Mesh
//     ArchFrontTop: THREE.Mesh
//     ArchBackLeft: THREE.Mesh
//     ArchBackRight: THREE.Mesh
//     ArchBackTop: THREE.Mesh
//     FrameLeft: THREE.Mesh
//     FrameRight: THREE.Mesh
//     FrameTop: THREE.Mesh
//   }
//   materials: {
//     melamin: THREE.MeshStandardMaterial
//     hpl: THREE.MeshStandardMaterial
//     Chrome: THREE.MeshStandardMaterial
//     Material: THREE.MeshStandardMaterial
//     ['Melamin.001']: THREE.MeshStandardMaterial
//     plywood: THREE.MeshStandardMaterial
//     mdf: THREE.MeshStandardMaterial
//   }
//   animations: GLTFAction[]
// }

// export function Model(props: JSX.IntrinsicElements['group']) {
//   const { nodes, materials } = useGLTF('/door.gltf') as GLTFResult
//   return (
//     <group {...props} dispose={null}>
//       <group position={[0.001, 2.16, 0.06]}>
//         <mesh geometry={nodes.ArchFrontLeft.geometry} material={materials['Melamin.001']} position={[-0.001, -2.16, -0.06]} />
//         <mesh geometry={nodes.ArchFrontRight.geometry} material={materials['Melamin.001']} position={[-0.001, -2.16, -0.06]} />
//         <mesh geometry={nodes.ArchFrontTop.geometry} material={materials['Melamin.001']} position={[-0.001, -2.16, -0.06]} />
//       </group>
//       <group position={[0.001, 2.16, 0.06]}>
//         <mesh geometry={nodes.ArchBackLeft.geometry} material={materials.plywood} position={[-0.001, -2.16, -0.06]} />
//         <mesh geometry={nodes.ArchBackRight.geometry} material={materials.plywood} position={[-0.001, -2.16, -0.06]} />
//         <mesh geometry={nodes.ArchBackTop.geometry} material={materials.plywood} position={[-0.001, -2.16, -0.06]} />
//       </group>
//       <group position={[0.001, 2.16, 0.06]}>
//         <mesh geometry={nodes.FrameLeft.geometry} material={materials.mdf} position={[-0.001, -2.16, -0.06]} />
//         <mesh geometry={nodes.FrameRight.geometry} material={materials.melamin} position={[-0.011, -2.16, -0.06]} />
//         <mesh geometry={nodes.FrameTop.geometry} material={materials.hpl} position={[-0.001, -2.16, -0.06]} />
//       </group>
//       <mesh geometry={nodes['2_Tali_Air_Horizontal'].geometry} material={materials.melamin} position={[-0.01, 0, 0.03]} />
//       <mesh geometry={nodes['3_Tali_Air_Horizontal'].geometry} material={materials.melamin} position={[-0.01, 0, 0.03]} />
//       <mesh geometry={nodes['3_Tali_Air_Vertikal'].geometry} material={materials.hpl} position={[-0.01, 0, 0.03]} />
//       <mesh geometry={nodes.Daun_Pintu_Polos.geometry} material={materials.hpl} position={[-0.01, 0, 0.03]} />
//       <mesh geometry={nodes.Engsel_Pintu.geometry} material={materials.Chrome} position={[0.805, 0.2, 0.018]} />
//       <mesh geometry={nodes['Handel_&_Kunci_Pintu'].geometry} material={materials.Chrome} position={[0.02, 0.94, 0.098]} />
//       <mesh geometry={nodes.Rangka_Honey_Comb001.geometry} material={materials.Material} position={[-0.01, 0, 0.03]} />
//     </group>
//   )
// }

// useGLTF.preload('/door.gltf')
