// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from 'react';
import { PageParamsProvider as PageParamsProvider__ } from '@plasmicapp/react-web/lib/host';

import { PlasmicHomepage } from '../components/plasmic/wisdoor_web/PlasmicHomepage';
import { useRouter } from 'next/router';
import { useGLTF } from '@react-three/drei';
import { extractPlasmicQueryData } from '@plasmicapp/react-web/lib/prepass';
import { PlasmicQueryDataProvider } from '@plasmicapp/react-web/lib/query';

// export async function getStaticProps() {
//   const queryCache = await extractPlasmicQueryData(<PlasmicHomepage />);
//   return {
//     props: { queryCache },
//   };
// }

function Homepage() {
  // Use PlasmicHomepage to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicHomepage are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, PlasmicHomepage is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).
  return (
    <PageParamsProvider__
      route={useRouter()?.pathname}
      params={useRouter()?.query}
      query={useRouter()?.query}
    >
      {/* <PlasmicQueryDataProvider prefetchedCache={queryCache}> */}
      <link
        rel="preload"
        href="https://raw.githack.com/pmndrs/drei-assets/456060a26bbeb8fdf79326f224b6d99b8bcce736/hdri/potsdamer_platz_1k.hdr"
        as="fetch"
      ></link>
      <PlasmicHomepage />
      {/* </PlasmicQueryDataProvider> */}
    </PageParamsProvider__>
  );
}

export default Homepage;
useGLTF.preload('/models/door.gltf');
