// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: t5hn1zAmdmxJoKmkXG4dPV
// Component: -Y2zUFW6j6F1

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { Navigation } from "../../navigation"; // plasmic-import: UiHqtQRdZ-A_/codeComponent
import { Hero } from "../../hero"; // plasmic-import: DLj-cPcbVVVA/codeComponent
import { TextReveal } from "../../magicui/text-reveal"; // plasmic-import: kTWRudp-inez/codeComponent
import { ShimmerButton } from "../../magicui/shimmer-button"; // plasmic-import: n12S44Pf_diF/codeComponent
import { ImageGradient } from "../../image-gradient"; // plasmic-import: BYKZmpg0gHCS/codeComponent
import { IconReveal } from "../../magicui/icon-reveal"; // plasmic-import: C_a578vM2Lk3/codeComponent
import { Reveal } from "../../magicui/reveal"; // plasmic-import: WZl_dCgRNxa8/codeComponent
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import { Project } from "../../project"; // plasmic-import: gt5pPBjlLVzP/codeComponent
import { Product } from "../../product"; // plasmic-import: tUhKBdzelJtb/codeComponent
import Footer from "../../Footer"; // plasmic-import: jyVfSNkVX5DJ/component
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";

import { useScreenVariants as useScreenVariantsqZb5Tz3BAq8Z } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: qZB5tz3bAQ8Z/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: t5hn1zAmdmxJoKmkXG4dPV/projectcss
import sty from "./PlasmicHome.module.css"; // plasmic-import: -Y2zUFW6j6F1/css

import PinSvgrepoComSvgIcon from "./icons/PlasmicIcon__PinSvgrepoComSvg"; // plasmic-import: OOrRfHur7WB6/icon
import BagSvgrepoComSvgIcon from "./icons/PlasmicIcon__BagSvgrepoComSvg"; // plasmic-import: eu2Gp3073zmn/icon
import DoorOpenSvgrepoComSvgIcon from "./icons/PlasmicIcon__DoorOpenSvgrepoComSvg"; // plasmic-import: 9Hn0B0fHgeN9/icon
import ConstructionSvgIcon from "./icons/PlasmicIcon__ConstructionSvg"; // plasmic-import: YRzU1IntfWEP/icon

createPlasmicElementProxy;

export type PlasmicHome__VariantMembers = {};
export type PlasmicHome__VariantsArgs = {};
type VariantPropType = keyof PlasmicHome__VariantsArgs;
export const PlasmicHome__VariantProps = new Array<VariantPropType>();

export type PlasmicHome__ArgsType = {};
type ArgPropType = keyof PlasmicHome__ArgsType;
export const PlasmicHome__ArgProps = new Array<ArgPropType>();

export type PlasmicHome__OverridesType = {
  root?: Flex__<"div">;
  navigation?: Flex__<typeof Navigation>;
  hero?: Flex__<typeof Hero>;
  textReveal?: Flex__<typeof TextReveal>;
  link?: Flex__<"a"> & Partial<LinkProps>;
  shimmerButton?: Flex__<typeof ShimmerButton>;
  about?: Flex__<"section">;
  imageGradient?: Flex__<typeof ImageGradient>;
  embedHtml?: Flex__<typeof Embed>;
  manufacturing?: Flex__<"div">;
  product?: Flex__<"div">;
  pvc?: Flex__<typeof Product>;
  hpl?: Flex__<typeof Product>;
  veener?: Flex__<typeof Product>;
  project?: Flex__<"div">;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultHomeProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHome__RenderFunc(props: {
  variants: PlasmicHome__VariantsArgs;
  args: PlasmicHome__ArgsType;
  overrides: PlasmicHome__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsqZb5Tz3BAq8Z()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicHome.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicHome.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicHome.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <Navigation
            data-plasmic-name={"navigation"}
            data-plasmic-override={overrides.navigation}
            alt={"Logo Wisdoor"}
            black={false}
            className={classNames("__wab_instance", sty.navigation)}
            image={"/plasmic/wisdoor_web/images/image1Png.png"}
          />

          <div className={classNames(projectcss.all, sty.freeBox__oPyea)}>
            <Hero
              data-plasmic-name={"hero"}
              data-plasmic-override={overrides.hero}
              alt={"Logo Wisdoor"}
              className={classNames("__wab_instance", sty.hero)}
              image={"/plasmic/wisdoor_web/images/pintu4RenderFinalPng.png"}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___5AgZ2)}
              >
                <TextReveal
                  data-plasmic-name={"textReveal"}
                  data-plasmic-override={overrides.textReveal}
                  characterClass={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "text-[40px] font-semibold"
                      : "text-[68px] font-semibold"
                  }
                  className={classNames("__wab_instance", sty.textReveal)}
                  text={"ENGINEERING\\nWOODEN DOOR\\nSPECIALIST"}
                />

                <PlasmicLink__
                  data-plasmic-name={"link"}
                  data-plasmic-override={overrides.link}
                  className={classNames(projectcss.all, projectcss.a, sty.link)}
                  component={Link}
                  href={`/door`}
                  platform={"nextjs"}
                >
                  <ShimmerButton
                    data-plasmic-name={"shimmerButton"}
                    data-plasmic-override={overrides.shimmerButton}
                    background={"#535353"}
                    borderRadius={"100px"}
                    className={classNames("__wab_instance", sty.shimmerButton)}
                    shimmerColor={"#ffffff"}
                    shimmerDuration={"3s"}
                    shimmerSize={"0.05em"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hXuq
                      )}
                    >
                      {"CUSTOM YOUR DOOR"}
                    </div>
                  </ShimmerButton>
                </PlasmicLink__>
              </Stack__>
            </Hero>
            <section
              data-plasmic-name={"about"}
              data-plasmic-override={overrides.about}
              className={classNames(projectcss.all, sty.about)}
              id={"about"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__icTrS
                )}
              >
                {"ABOUT US"}
              </div>
              <ImageGradient
                data-plasmic-name={"imageGradient"}
                data-plasmic-override={overrides.imageGradient}
                alt={"Logo Wisdoor"}
                className={classNames("__wab_instance", sty.imageGradient)}
                gradientBottomBlack={false}
                gradientTopWhite={true}
                image={
                  "/plasmic/wisdoor_web/images/whatsAppImage20241028At121213PmJpeg.jpg"
                }
              />

              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__k6GPl)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pqYBy
                  )}
                >
                  {"ABOUT US"}
                </div>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__xuOgE)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__bfHUv)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__skDUw
                      )}
                    >
                      {
                        "Founded in 1994, PT. Wiratama Inti Sentosa began as a wood manufacturing company specializing in kiln drying and molding for timber furniture. We later expanded into finger joint laminating for door cores and producing our own furniture, exporting to markets such as Taiwan, Singapore, South Africa, Netherlands, and Korea."
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__ujNlX)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hdtXh
                      )}
                    >
                      {
                        "Leveraging our proven expertise in exporting door cores, we now focus on serving a diverse range of markets in the local door industry. From small residential homes to luxury hotels, we specialize in delivering tailored solutions to meet the needs of every space, emphasizing quality and versatility."
                      }
                    </div>
                  </div>
                </Stack__>
                <div className={classNames(projectcss.all, sty.freeBox__axdpY)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__qrdzC)}
                  >
                    <IconReveal
                      className={classNames(
                        "__wab_instance",
                        sty.iconReveal__jTRr9
                      )}
                    >
                      <PinSvgrepoComSvgIcon
                        className={classNames(projectcss.all, sty.svg__k4Jdz)}
                        role={"img"}
                      />
                    </IconReveal>
                    <Reveal
                      className={classNames(
                        "__wab_instance",
                        sty.reveal__pgL4C
                      )}
                      delay={0.1}
                      duration={0.5}
                    >
                      <Embed
                        data-plasmic-name={"embedHtml"}
                        data-plasmic-override={overrides.embedHtml}
                        className={classNames("__wab_instance", sty.embedHtml)}
                        code={"3,975.32 m<sup>2</sup>"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iLkes
                        )}
                      >
                        {"Range Area"}
                      </div>
                    </Reveal>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__h9MrN)}
                  >
                    <IconReveal
                      className={classNames(
                        "__wab_instance",
                        sty.iconReveal___08OKs
                      )}
                      delay={0.25}
                      duration={0.25}
                    >
                      <BagSvgrepoComSvgIcon
                        className={classNames(projectcss.all, sty.svg__tdwDv)}
                        role={"img"}
                      />
                    </IconReveal>
                    <Reveal
                      className={classNames(
                        "__wab_instance",
                        sty.reveal__jOj3I
                      )}
                      delay={0.35}
                      duration={0.5}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tJlf
                        )}
                      >
                        {"20+"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__utbZb
                        )}
                      >
                        {"Years"}
                      </div>
                    </Reveal>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ePsfp)}
                  >
                    <IconReveal
                      className={classNames(
                        "__wab_instance",
                        sty.iconReveal__vls6W
                      )}
                      delay={0.5}
                      duration={0.5}
                    >
                      <DoorOpenSvgrepoComSvgIcon
                        className={classNames(projectcss.all, sty.svg__myzhv)}
                        role={"img"}
                      />
                    </IconReveal>
                    <Reveal
                      className={classNames(
                        "__wab_instance",
                        sty.reveal__jOijy
                      )}
                      delay={0.6}
                      duration={0.5}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___03UCl
                        )}
                      >
                        {"2000 Doors"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__b7LEr
                        )}
                      >
                        {"Per Month"}
                      </div>
                    </Reveal>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__q07P5)}
                  >
                    <IconReveal
                      className={classNames(
                        "__wab_instance",
                        sty.iconReveal__bQyFu
                      )}
                      delay={0.75}
                      duration={0.75}
                    >
                      <ConstructionSvgIcon
                        className={classNames(projectcss.all, sty.svg___8RgGo)}
                        role={"img"}
                      />
                    </IconReveal>
                    <Reveal
                      className={classNames(
                        "__wab_instance",
                        sty.reveal__evplK
                      )}
                      delay={0.85}
                      duration={0.5}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__c7P1D
                        )}
                      >
                        {"1000 Door Frames"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__f2AeL
                        )}
                      >
                        {"Per Month"}
                      </div>
                    </Reveal>
                  </div>
                </div>
              </Stack__>
            </section>
            <div
              data-plasmic-name={"manufacturing"}
              data-plasmic-override={overrides.manufacturing}
              className={classNames(projectcss.all, sty.manufacturing)}
              id={"manufacturing"}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__dGqZ6)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bWtga
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#968383" }}
                    >
                      {"MANUFACTURING"}
                    </span>
                  </React.Fragment>
                </div>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns___2GVr)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__lq3Ac)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dei0
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Wijaya Door: \nCrafted to Perfection, \nDelivered with Speed."
                        : "Wijaya Door: \nCrafted to Perfection,\nDelivered with Speed."}
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__eedTx)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yuwdD
                      )}
                    >
                      {
                        "Our R&D division drives continuous innovation, supported by advanced Italian-made technology, including CNC machines, edging and vacuum membrane machines, and CAD/CAM software. These high-investment tools enable precision, customization, and durability in every product. \n\nAt Wijaya Door, we uphold the highest standards in durability, timely delivery, and integrity\u2014creating doors that last, tailored to the unique needs of our clients. Through relentless pursuit of quality and on-time delivery, we\u2019re committed to remaining a trusted name in the industry."
                      }
                    </div>
                  </div>
                </Stack__>
              </Stack__>
              <Project
                className={classNames("__wab_instance", sty.project___3HcDv)}
                projectImages={(() => {
                  const __composite = [
                    { image: null, alt: "Logo Wisdoor" },
                    { image: null, alt: "Logo Wisdoor" },
                    { image: null, alt: "Logo Wisdoor" },
                    { image: null, alt: "Logo Wisdoor" },
                    { image: null, alt: "Logo Wisdoor" },
                    { image: null, alt: "Logo Wisdoor" },
                    { image: null, alt: "Logo Wisdoor" },
                    { image: null, alt: "Logo Wisdoor" }
                  ];
                  __composite["0"]["image"] =
                    "https://site-assets.plasmic.app/d601bc492c210f9cd29a247d6d85ce89.png";
                  __composite["1"]["image"] =
                    "https://site-assets.plasmic.app/6aad20d2afc3f09a14019ce396e9c717.png";
                  __composite["2"]["image"] =
                    "https://site-assets.plasmic.app/b048c13b5144bcee10742287a0b2cf04.png";
                  __composite["3"]["image"] =
                    "https://site-assets.plasmic.app/fcf84f69eb6d0550f27abe39f42853cf.png";
                  __composite["4"]["image"] =
                    "https://site-assets.plasmic.app/474cd10b2d4db1dcd81bd608fafbf2d9.png";
                  __composite["5"]["image"] =
                    "https://site-assets.plasmic.app/543632e0eaa7546e507949c6ec4bbc15.png";
                  __composite["6"]["image"] =
                    "https://site-assets.plasmic.app/1aeb938b83a8f92a13020a8d61cca036.png";
                  __composite["7"]["image"] =
                    "https://site-assets.plasmic.app/d235a0081ea762282820ad5e30b7b370.png";
                  return __composite;
                })()}
              />
            </div>
            <div
              data-plasmic-name={"product"}
              data-plasmic-override={overrides.product}
              className={classNames(projectcss.all, sty.product)}
              id={"product"}
            >
              <Product
                data-plasmic-name={"pvc"}
                data-plasmic-override={overrides.pvc}
                className={classNames("__wab_instance", sty.pvc)}
                isBottom={false}
                productImages={(() => {
                  const __composite = [
                    { image: null, alt: null },
                    { image: null, alt: null }
                  ];
                  __composite["0"]["image"] =
                    "https://site-assets.plasmic.app/2b519c174f5ba731b50c6600722bcd8d.png";
                  __composite["0"]["alt"] = "Produk 1";
                  __composite["1"]["image"] =
                    "https://site-assets.plasmic.app/5a5272ee297aa1013c98935f67b0a42e.png";
                  __composite["1"]["alt"] = "Product 2";
                  return __composite;
                })()}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ctUv7
                  )}
                >
                  {"PRODUCT"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uYZey
                  )}
                >
                  {"PVC SERIES"}
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__wFZj)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__iPcy
                    )}
                  >
                    {"SPECIFICATION"}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__gOUt)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__sleYp)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nIpjw
                        )}
                      >
                        {"SURFACE"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__snHTh)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___710O
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__ever8
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__lHsRi
                                )}
                              >
                                {
                                  "Entrance Door (Plywood + PVC Fin + Honeycomb)\n"
                                }
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__uEbso
                                )}
                              >
                                {"Room Door (MDF + PVC Fin)\n"}
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__mWu6U
                                )}
                              >
                                {"Toilet Door (Plywood + PVC Fin)"}
                              </li>
                            </ul>
                          }
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__cRsQd)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__r1S09)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__e9BYn
                        )}
                      >
                        {"DOOR SIZE"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__yrVtb)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__l9WGv
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__frS3
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__bv7Jt
                                )}
                              >
                                {
                                  "Entrance Door & Room Door (T) 36 X (L) 820 x (P) 2100"
                                }
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li___35VGv
                                )}
                              >
                                {"Toilet Door (T) 36 x (L) 720 x (P) 2100"}
                              </li>
                            </ul>
                          }
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__qsm31)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__yWb1)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yH4Z
                        )}
                      >
                        {"FRAME SIZE"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__c0VVg)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zO8Z0
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul___2YSqp
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__peChd
                                )}
                              >
                                {"Entrance Door & Room Door (L) 888 x (P) 2138"}
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__lbHmQ
                                )}
                              >
                                {"Toilet Door (L) 788 x (P) 2138"}
                              </li>
                            </ul>
                          }
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__oS4Jv)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox___7BTc)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__spp4D
                        )}
                      >
                        {"OPENING SIZE"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__lwldw)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gcTas
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__kC1L
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__lq6Si
                                )}
                              >
                                {"Entrance Door & Room Door (L) 898 x (P) 2143"}
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__sbeHh
                                )}
                              >
                                {"Toilet Door (L) 798 x (P) 2143"}
                              </li>
                            </ul>
                          }
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>
                    </div>
                  </div>
                </div>
              </Product>
              <Product
                data-plasmic-name={"hpl"}
                data-plasmic-override={overrides.hpl}
                className={classNames("__wab_instance", sty.hpl)}
                isBottom={false}
                productImages={(() => {
                  const __composite = [{ image: null, alt: null }];
                  __composite["0"]["image"] =
                    "https://site-assets.plasmic.app/5c498b490a3917cccaa11ba3cdf97a60.png";
                  __composite["0"]["alt"] = "Produk 1";
                  return __composite;
                })()}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dJb4V
                  )}
                >
                  {"PRODUCT"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dtUIt
                  )}
                >
                  {"HPL SERIES"}
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__doSqK)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__evbSq
                    )}
                  >
                    {"SPECIFICATION"}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__n8FuJ)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__nYsd9)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jf4Em
                        )}
                      >
                        {"SURFACE"}
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___7TpR4
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nl4FD
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__kHfq5
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__zu1ZU
                                )}
                              >
                                {
                                  "Entrance Door (Plywood + HPL Fin + Honeycomb)"
                                }
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__diarD
                                )}
                              >
                                {"Room Door (MDF + HPL Fin)"}
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__sy0Xz
                                )}
                              >
                                {"Toilet Door (Plywood + HPL Fin)"}
                              </li>
                            </ul>
                          }
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___7TGpD)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__nXzVv)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__b8Cuz
                        )}
                      >
                        {"DOOR SIZE"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__juoW)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___5I7
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__lWn5C
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__b2NHa
                                )}
                              >
                                {
                                  "Entrance Door & Room Door (T) 36 X (L) 820 x (P) 2100\n"
                                }
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__wrVPe
                                )}
                              >
                                {"Toilet Door (T) 36 x (L) 720 x (P) 2100"}
                              </li>
                            </ul>
                          }
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__shyOs)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__pwAv8)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yhLda
                        )}
                      >
                        {"FRAME SIZE"}
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___5Vu0I
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wrbQr
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__o5Qcq
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__mOp9J
                                )}
                              >
                                {
                                  "Entrance Door & Room Door (L) 888 x (P) 2138\n"
                                }
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__vn8Tb
                                )}
                              >
                                {"Toilet Door (L) 788 x (P) 2138"}
                              </li>
                            </ul>
                          }
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___23NVa)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__rr6RM)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__n8Pn
                        )}
                      >
                        {"OPENING SIZE"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__noW5T)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___13TJ
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__wp6Ud
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li___9Mk6X
                                )}
                              >
                                {
                                  "Entrance Door & Room Door (L) 898 x (P) 2143\n"
                                }
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__kkEo1
                                )}
                              >
                                {"Toilet Door (L) 798 x (P) 2143"}
                              </li>
                            </ul>
                          }
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>
                    </div>
                  </div>
                </div>
              </Product>
              <Product
                data-plasmic-name={"veener"}
                data-plasmic-override={overrides.veener}
                className={classNames("__wab_instance", sty.veener)}
                isBottom={true}
                productImages={(() => {
                  const __composite = [
                    { image: null, alt: null },
                    { image: null, alt: null }
                  ];
                  __composite["0"]["image"] =
                    "https://site-assets.plasmic.app/f45968fe35122b12a19d6ed639c22817.avif";
                  __composite["0"]["alt"] = "Produk 1";
                  __composite["1"]["image"] =
                    "https://site-assets.plasmic.app/f45968fe35122b12a19d6ed639c22817.avif";
                  __composite["1"]["alt"] = "Product 2";
                  return __composite;
                })()}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__d8Lic
                  )}
                >
                  {"PRODUCT"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___5LqdG
                  )}
                >
                  {"VENEER SERIES"}
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__mqIpJ)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__p5Zl
                    )}
                  >
                    {"SPECIFICATION"}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__dYyzT)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__o4U9R)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mgmHz
                        )}
                      >
                        {"SURFACE"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__wR0L2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__sxGG
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__oAIck
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__vHs7B
                                )}
                              >
                                {
                                  "Entrance Door (Plywood + Veneer Fin + Honeycomb)"
                                }
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li___06Dj7
                                )}
                              >
                                {"Room Door (MDF + Veneer Fin)"}
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__t5KK
                                )}
                              >
                                {"Toilet Door (Plywood + Veneer Fin)"}
                              </li>
                            </ul>
                          }
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__w0Pj)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__uoSic)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ytI93
                        )}
                      >
                        {"DOOR SIZE"}
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___83U2K
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__dq16Z
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__paLkk
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li___3MYp
                                )}
                              >
                                {
                                  "Entrance Door & Room Door (T) 36 X (L) 820 x (P) 2100\n"
                                }
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__j3ZnJ
                                )}
                              >
                                {"Toilet Door (T) 36 x (L) 720 x (P) 2100"}
                              </li>
                            </ul>
                          }
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___83YTs)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__tgkYy)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pzliT
                        )}
                      >
                        {"FRAME SIZE"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__sSxjQ)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___2XBt
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__zj90J
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__tUg4E
                                )}
                              >
                                {
                                  "Entrance Door & Room Door (L) 888 x (P) 2138\n"
                                }
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__o7O3R
                                )}
                              >
                                {"Toilet Door (L) 788 x (P) 2138"}
                              </li>
                            </ul>
                          }
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__dcAf5)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__eFwDy)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wq34
                        )}
                      >
                        {"OPENING SIZE"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__zaaEz)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tL6O
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__jjogC
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__zSokN
                                )}
                              >
                                {"Entrance Door & Room Door (L) 898 x (P) 2143"}
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__iT4FB
                                )}
                              >
                                {"Toilet Door (L) 798 x (P) 2143"}
                              </li>
                            </ul>
                          }
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>
                    </div>
                  </div>
                </div>
              </Product>
            </div>
            <div
              data-plasmic-name={"project"}
              data-plasmic-override={overrides.project}
              className={classNames(projectcss.all, sty.project)}
              id={"project"}
            >
              <div className={classNames(projectcss.all, sty.columns__dilKh)}>
                <div className={classNames(projectcss.all, sty.column__vIntc)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tANuX
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "PROJECT REFERENCE"
                      : "PROJECT\nREFERENCE"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__gx487)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rYiXv
                    )}
                  >
                    {
                      "Engineered for strength, crafted with care. \nDoors that stand the test of time."
                    }
                  </div>
                </div>
              </div>
              <Project
                className={classNames("__wab_instance", sty.project__mEwZz)}
                projectImages={(() => {
                  const __composite = [
                    { image: null, alt: "Logo Wisdoor" },
                    { image: null, alt: "Logo Wisdoor" }
                  ];
                  __composite["0"]["image"] =
                    "https://site-assets.plasmic.app/a3a4656c9e4957a78b9e1ee960b16755.png";
                  __composite["1"]["image"] =
                    "https://site-assets.plasmic.app/7db7bfde388ea1b49cf1d5de4916dfa9.png";
                  return __composite;
                })()}
              />
            </div>
            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navigation",
    "hero",
    "textReveal",
    "link",
    "shimmerButton",
    "about",
    "imageGradient",
    "embedHtml",
    "manufacturing",
    "product",
    "pvc",
    "hpl",
    "veener",
    "project",
    "footer"
  ],
  navigation: ["navigation"],
  hero: ["hero", "textReveal", "link", "shimmerButton"],
  textReveal: ["textReveal"],
  link: ["link", "shimmerButton"],
  shimmerButton: ["shimmerButton"],
  about: ["about", "imageGradient", "embedHtml"],
  imageGradient: ["imageGradient"],
  embedHtml: ["embedHtml"],
  manufacturing: ["manufacturing"],
  product: ["product", "pvc", "hpl", "veener"],
  pvc: ["pvc"],
  hpl: ["hpl"],
  veener: ["veener"],
  project: ["project"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navigation: typeof Navigation;
  hero: typeof Hero;
  textReveal: typeof TextReveal;
  link: "a";
  shimmerButton: typeof ShimmerButton;
  about: "section";
  imageGradient: typeof ImageGradient;
  embedHtml: typeof Embed;
  manufacturing: "div";
  product: "div";
  pvc: typeof Product;
  hpl: typeof Product;
  veener: typeof Product;
  project: "div";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHome__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHome__VariantsArgs;
    args?: PlasmicHome__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHome__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHome__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHome__ArgProps,
          internalVariantPropNames: PlasmicHome__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navigation: makeNodeComponent("navigation"),
    hero: makeNodeComponent("hero"),
    textReveal: makeNodeComponent("textReveal"),
    link: makeNodeComponent("link"),
    shimmerButton: makeNodeComponent("shimmerButton"),
    about: makeNodeComponent("about"),
    imageGradient: makeNodeComponent("imageGradient"),
    embedHtml: makeNodeComponent("embedHtml"),
    manufacturing: makeNodeComponent("manufacturing"),
    product: makeNodeComponent("product"),
    pvc: makeNodeComponent("pvc"),
    hpl: makeNodeComponent("hpl"),
    veener: makeNodeComponent("veener"),
    project: makeNodeComponent("project"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Wijaya Door",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
